# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Messaging.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fMessaging.proto\x12\tmessaging\">\n\x07\x43hannel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x17\n\x0fpendingMessages\x18\x03 \x01(\t\"1\n\x0b\x43hannelList\x12\"\n\x06\x63\x61nais\x18\x01 \x03(\x0b\x32\x12.messaging.Channel\"=\n\tQueueName\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.messaging.QueueType\"B\n\x0b\x43hannelName\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.messaging.QueueType\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"2\n\x0eMessageRequest\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"4\n\x0fMessageResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\x1a\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"l\n\x0bMessageList\x12$\n\x08messages\x18\x01 \x03(\x0b\x32\x12.messaging.Message\x12\x13\n\x0b\x43hannelName\x18\x02 \x01(\t\x12\"\n\x04type\x18\x03 \x01(\x0e\x32\x14.messaging.QueueType\"\x07\n\x05\x45mpty*&\n\tQueueType\x12\x0b\n\x07SIMPLES\x10\x00\x12\x0c\n\x08MULTIPLO\x10\x01\x32\x95\x04\n\x10MessagingService\x12\x38\n\nNewChannel\x12\x16.messaging.ChannelName\x1a\x12.messaging.Message\x12\x39\n\rDeleteChannel\x12\x14.messaging.QueueName\x1a\x12.messaging.Message\x12\x38\n\x0cListChannels\x12\x10.messaging.Empty\x1a\x16.messaging.ChannelList\x12G\n\x0eSendOneMessage\x12\x19.messaging.MessageRequest\x1a\x1a.messaging.MessageResponse\x12J\n\x14SendMultipleMessages\x12\x16.messaging.MessageList\x1a\x1a.messaging.MessageResponse\x12=\n\x0fReceiveMessages\x12\x14.messaging.QueueName\x1a\x12.messaging.Message0\x01\x12@\n\x14ReceiveSingleMessage\x12\x14.messaging.QueueName\x1a\x12.messaging.Message\x12<\n\x0eStreamMessages\x12\x14.messaging.QueueName\x1a\x12.messaging.Message0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Messaging_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUEUETYPE']._serialized_start=529
  _globals['_QUEUETYPE']._serialized_end=567
  _globals['_CHANNEL']._serialized_start=30
  _globals['_CHANNEL']._serialized_end=92
  _globals['_CHANNELLIST']._serialized_start=94
  _globals['_CHANNELLIST']._serialized_end=143
  _globals['_QUEUENAME']._serialized_start=145
  _globals['_QUEUENAME']._serialized_end=206
  _globals['_CHANNELNAME']._serialized_start=208
  _globals['_CHANNELNAME']._serialized_end=274
  _globals['_MESSAGEREQUEST']._serialized_start=276
  _globals['_MESSAGEREQUEST']._serialized_end=326
  _globals['_MESSAGERESPONSE']._serialized_start=328
  _globals['_MESSAGERESPONSE']._serialized_end=380
  _globals['_MESSAGE']._serialized_start=382
  _globals['_MESSAGE']._serialized_end=408
  _globals['_MESSAGELIST']._serialized_start=410
  _globals['_MESSAGELIST']._serialized_end=518
  _globals['_EMPTY']._serialized_start=520
  _globals['_EMPTY']._serialized_end=527
  _globals['_MESSAGINGSERVICE']._serialized_start=570
  _globals['_MESSAGINGSERVICE']._serialized_end=1103
# @@protoc_insertion_point(module_scope)
