# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Subscribe.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fSubscribe.proto\x12\tsubscribe\"a\n\x0b\x43hannelType\x12\x13\n\x0b\x63hannelName\x18\x01 \x01(\t\x12)\n\x0b\x63hannelType\x18\x02 \x01(\x0e\x32\x14.subscribe.QueueType\x12\x12\n\nclientName\x18\x03 \x01(\t\"\x1a\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\" \n\nReturnList\x12\x12\n\nassinantes\x18\x01 \x01(\t\"\x07\n\x05\x45mpty*&\n\tQueueType\x12\x0b\n\x07SIMPLES\x10\x00\x12\x0c\n\x08MULTIPLO\x10\x01\x32\xc2\x01\n\x10SubscribeService\x12\x37\n\tSubscribe\x12\x16.subscribe.ChannelType\x1a\x12.subscribe.Message\x12\x39\n\x0bUnsubscribe\x12\x16.subscribe.ChannelType\x1a\x12.subscribe.Message\x12:\n\x0fListSubscribers\x12\x10.subscribe.Empty\x1a\x15.subscribe.ReturnListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Subscribe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUEUETYPE']._serialized_start=200
  _globals['_QUEUETYPE']._serialized_end=238
  _globals['_CHANNELTYPE']._serialized_start=30
  _globals['_CHANNELTYPE']._serialized_end=127
  _globals['_MESSAGE']._serialized_start=129
  _globals['_MESSAGE']._serialized_end=155
  _globals['_RETURNLIST']._serialized_start=157
  _globals['_RETURNLIST']._serialized_end=189
  _globals['_EMPTY']._serialized_start=191
  _globals['_EMPTY']._serialized_end=198
  _globals['_SUBSCRIBESERVICE']._serialized_start=241
  _globals['_SUBSCRIBESERVICE']._serialized_end=435
# @@protoc_insertion_point(module_scope)
